# Generated by Django 3.2.4 on 2024-01-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
