# Generated by Django 3.2.4 on 2024-01-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_instructor_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
