# Generated by Django 3.2.4 on 2024-01-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_paymentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='payment_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
