# Generated by Django 3.2.4 on 2024-01-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_auto_20240118_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
