# Generated by Django 3.2.4 on 2024-01-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_auto_20240118_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='order',
            field=models.IntegerField(default=0, help_text='Used to determine the order of categories'),
        ),
    ]
