# Generated by Django 3.2.4 on 2024-01-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_aiproductimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproduct',
            name='image_url_1',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='aiproduct',
            name='image_url_2',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='aiproduct',
            name='image_url_3',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='aiproduct',
            name='image_url_4',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
