# Generated by Django 3.2.4 on 2024-01-18 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_auto_20240118_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.aiproduct'),
        ),
    ]
