# Generated by Django 3.2.4 on 2024-01-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0022_auto_20240119_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
