# Generated by Django 3.2.4 on 2024-01-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0023_auto_20240121_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='image',
        ),
        migrations.AddField(
            model_name='speaker',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
