# Generated by Django 3.2.4 on 2024-01-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0024_auto_20240122_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='speakers'),
        ),
    ]
