# Generated by Django 3.2.4 on 2024-01-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_speaker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lessons',
            field=models.TextField(null=True),
        ),
    ]
